version: '3.9'
services:
  hallvoice:
    hostname: hallvoice
    build:
      dockerfile: Dockerfile.porte
    volumes:
      - ./src:/hallvoice
      - ./config:/hallvoice/conf
    devices:
      - /dev/bus/usb:/dev/bus/usb
    networks:
      - default
  purge_api:
    hostname: purgeAPI
    build:
      dockerfile: Dockerfile.API
    volumes:
      - ./src:/purgeAPI
    networks:
      - default
  redis:
    image: redis:latest
    hostname: redis
    networks:
      - default
networks:
  default:
